import './globals.css'
import { SideBar } from '@/components/SideBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <title>{metadata.title}</title>
      </head>
      <body>
          <div className="flex">

            {/* SideBar */}
            <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[18rem]">
              <SideBar />
            </div>

            {/* ClientProvide - Notification */}

            <div className="bg-[#343541] flex-1">{children}</div>
          </div>
      </body>
    </html>
  )
}
